# Numpy Tutorial

In [1]:
!pip install numpy

## 1. 넘파이 소개

In [2]:
import numpy as np
import time

### Numpy 속도 테스트

In [3]:
#test speed
def sum_trad():
    start = time.time()
    X = range(10000000)
    Y = range(10000000)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - start
    
def sum_numpy():
    start = time.time()
    X = np.arange(10000000) 
    Y = np.arange(10000000) 
    Z=X+Y
    return time.time() - start

print ('time sum:',sum_trad(),'  time sum numpy:',sum_numpy())

time sum: 8.752399921417236   time sum numpy: 0.12499189376831055


## 2. 배열 생성

### 2.1 단일 값으로 초기화

In [4]:
# 단일 값으로 초기화된 배열 생성
print(np.full((3, 3), np.inf))
print(np.full((3, 3), 10.1))

[[inf inf inf]
 [inf inf inf]
 [inf inf inf]]
[[10.1 10.1 10.1]
 [10.1 10.1 10.1]
 [10.1 10.1 10.1]]


In [5]:
# 배열을 단일 값으로 리셋
arr = np.array([10, 20, 33], float)
print(arr)

[10. 20. 33.]


In [6]:
arr.fill(1)
print(arr)

[1. 1. 1.]


### 2.2 랜덤 초기화

In [7]:
# 정수 순열로 초기화된 배열 생성
np.random.permutation(3)

array([1, 0, 2])

In [8]:
# 균등분포로 초기화된 배열 생성
np.random.random(5)

array([0.49268642, 0.73910484, 0.29046511, 0.03140259, 0.13389864])

In [9]:
# 균등분포로 초기화된 2차원 배열 생성
np.random.rand(2,3)

array([[0.05621246, 0.26423437, 0.52018664],
       [0.96686911, 0.84310316, 0.0886853 ]])

In [10]:
# 정규분포로 초기화된 배열 생성
np.random.normal(0,1,5) # 평균, 표준 편차

array([ 0.46859293,  2.81061461,  0.78674686,  0.62688269, -1.82745497])

In [11]:
# 다변량 정규분포로 초기화된 2차원 배열 생성
np.random.multivariate_normal([10, 0], [[3, 1], [1, 4]], size=[5,]) # 평균, 공분산, 배열 형태

array([[ 7.48487466, -0.57755571],
       [11.33813017, -0.23236418],
       [10.6453999 , -0.65072269],
       [ 6.16884455, -1.61783138],
       [12.02430554,  0.26126015]])

### 2.3 리스트에서 생성

In [12]:
#리스트에서 배열 생성
arr = np.array([2, 6, 5, 9], float)
print (arr)
print (type(arr))

[2. 6. 5. 9.]
<class 'numpy.ndarray'>


In [13]:
# 배열에서 리스트로 변환
arr = np.array([1, 2, 3], float)
print (arr.tolist())
print (list(arr))

[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


### 2.4 배열 복사

In [14]:
arr = np.array([1, 2, 3], float)
arr1 = arr
arr2 = arr.copy()
arr[0] = 0
print (arr)
print (arr1)
print (arr2)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


### 2.5 단위 행렬

In [15]:
np.identity(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 2.6 영행렬, 1행렬

In [17]:
np.zeros(6, dtype=int)

array([0, 0, 0, 0, 0, 0])

In [18]:
np.ones((2,3), dtype=float)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
# 주어진 배열과 동일한 차원의 영행렬, 1행렬 생성
arr = np.array([[13, 32, 31], [64, 25, 76]], float)
np.zeros_like(arr)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones_like(arr)

array([[1., 1., 1.],
       [1., 1., 1.]])

## 3. 배열 관리

### 3.1 배열의 크기와 데이터 타입

In [21]:
# 배열의 모양 확인
arr.shape

(2, 3)

In [22]:
# 1차원의 길이
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
len(arr)

2

In [23]:
# 데이터 타입 확인
arr.dtype

dtype('float64')

In [25]:
# 데이터 타입 변환
int_arr = matrix.astype(np.int32)
int_arr

NameError: name 'matrix' is not defined

### 3.2 배열 읽기/쓰기

In [26]:
arr = np.array([2., 6., 5., 5.])
print(arr[:3])
print(arr[3])
arr[0] = 5.
print(arr)

[2. 6. 5.]
5.0
[5. 6. 5. 5.]


### 3.3 배열 슬라이싱

In [27]:
# 슬라이싱
matrix = np.array([[ 4., 5., 6.], [2, 3, 6]], float)
print(matrix)

[[4. 5. 6.]
 [2. 3. 6.]]


In [28]:
arr = np.array([[ 4., 5., 6.], [ 2., 3., 6.]], float)
print(arr[1:2,2:3])
print(arr[1,:])
print(arr[:,2])
print(arr[-1:,-2:])

[[6.]]
[2. 3. 6.]
[6. 6.]
[[3. 6.]]


### 3.4 배열 쿼리

In [29]:
# 인덱스 배열로 쿼리
arr1 = np.array([1, 4, 5, 9], float)
arr2 = np.array([0, 1, 1, 3, 1, 1, 1], int)
print(arr1[arr2])

[1. 4. 4. 9. 4. 4. 4.]


In [30]:
# 다차원 배열 인덱스 배열로 쿼리
arr1 = np.array([[1, 2], [5, 13]], float)
arr2 = np.array([1, 0, 0, 1], int)
arr3 = np.array([1, 1, 0, 1], int)
print(arr1[arr2,arr3])

[13.  2.  1. 13.]


In [31]:
# 논리 행렬로 쿼리
arr = np.arange(25).reshape(5,5)
print(arr % 2 == 0)
arr[arr % 2 == 0] = 0
print(arr)

[[ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]
 [False  True False  True False]
 [ True False  True False  True]]
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


In [32]:
# where 조건으로 쿼리
a = np.arange(10)
print(a)
np.where(a < 5, a, 10*a)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

### 3.5 중복 제거

In [33]:
arr = np.array([2., 6., 5., 5.])
print(np.unique(arr))

[2. 5. 6.]


### 3.6 정렬/섞기

In [34]:
# 정렬
np.sort(arr)

array([2., 5., 5., 6.])

In [35]:
# 정렬해서 인덱스 배열 생성
np.argsort(arr)

array([0, 2, 3, 1], dtype=int64)

In [36]:
# 랜덤하게 섞기
np.random.shuffle(arr)
arr

array([5., 5., 2., 6.])

In [37]:
# 배열 비교
np.array_equal(arr,np.array([1,3,2]))

False

### 3.7 1차원 배열로 펴기

In [38]:
# Flattening
arr = np.array([[10, 29, 23], [24, 25, 46]], float)
print(arr)
print(arr.flatten())

[[10. 29. 23.]
 [24. 25. 46.]]
[10. 29. 23. 24. 25. 46.]


### 3.8 재배열

In [39]:
# 배열의 재배열
arr = np.array(range(8), float)
print(arr)
arr = arr.reshape((4,2))
print(arr)
print(arr.shape)

[0. 1. 2. 3. 4. 5. 6. 7.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]
(4, 2)


### 3.9 전치 행렬

In [40]:
arr = np.array(range(6), float).reshape((2, 3))
print(arr)
print(arr.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [41]:
# 행렬의 T 속성으로 전치하기
matrix = np.arange(15).reshape((3, 5))
print(matrix)
print(matrix .T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### 3.10 차원 늘리기

In [42]:
# newaxis로 차원 늘리기
arr = np.array([14, 32, 13], float)
print(arr)
print(arr[:,np.newaxis])
print(arr[:,np.newaxis].shape)
print(arr[np.newaxis,:])
print(arr[np.newaxis,:].shape)

[14. 32. 13.]
[[14.]
 [32.]
 [13.]]
(3, 1)
[[14. 32. 13.]]
(1, 3)


### 3.11 배열 결합

In [43]:
arr1 = np.array([[11, 12], [32, 42]], float)
arr2 = np.array([[54, 26], [27, 28]], float)
print(np.concatenate((arr1,arr2)))

# 1차원 방향으로 결합
print(np.concatenate((arr1,arr2), axis=0))

# 2차원 방향으로 결합
print(np.concatenate((arr1,arr2), axis=1))

[[11. 12.]
 [32. 42.]
 [54. 26.]
 [27. 28.]]
[[11. 12.]
 [32. 42.]
 [54. 26.]
 [27. 28.]]
[[11. 12. 54. 26.]
 [32. 42. 27. 28.]]


### 3.12 배열 쌓기

In [44]:
x = np.array([2, 3, 4]) 
y = np.array([3, 4, 5])

In [45]:
# 1차원으로 쌓기 (행으로 쌓기)
np.stack((x, y))

array([[2, 3, 4],
       [3, 4, 5]])

In [46]:
# 2차원으로 쌓기 (열로 쌓기)
np.stack((x, y), axis=-1)

array([[2, 3],
       [3, 4],
       [4, 5]])

## 4. 배열 연산

### 4.1 산술연산

In [47]:
#array operations
arr1 = np.array([1,2,3], float)
arr2 = np.array([1,2,3], float)
print(arr1+arr2)
print(arr1-arr2)
print(arr1 * arr2)
print(arr2 / arr1)
print(arr1 % arr2)
print(arr2**arr1)

[2. 4. 6.]
[0. 0. 0.]
[1. 4. 9.]
[1. 1. 1.]
[0. 0. 0.]
[ 1.  4. 27.]


### 4.2 브로드캐스팅

In [48]:
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)

print(arr1)
print(arr2)
print(arr1 + arr2)

[[0. 0.]
 [0. 0.]]
[1. 2.]
[[1. 2.]
 [1. 2.]]


In [49]:
# 배열의 브로드캐스팅 방식을 명시하고 싶다면 newaxis 상수를 이용해서 확장해야 할 축을 지정
arr1 = np.zeros((2,2), float)
arr2 = np.array([1., 2.], float)
print( arr1 + arr2[np.newaxis,:])
print(arr1 + arr2[:,np.newaxis])

[[1. 2.]
 [1. 2.]]
[[1. 1.]
 [2. 2.]]


### 4.3 논리 연산

In [50]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
X1 = arr%2 == 0
print(X1)

[[False  True False]
 [ True False  True]]


In [51]:
X2 = arr >= 4
print(X2)

[[False False False]
 [ True  True  True]]


In [52]:
X3 = X1*1
print(X3)

[[0 1 0]
 [1 0 1]]


In [53]:
np.logical_and(X1, X2)

array([[False, False, False],
       [ True, False,  True]])

## 5. 선형대수 연산

### 5.1 벡터의 곱

In [54]:
arr1 = np.array([12, 43, 10], float)
arr2 = np.array([21, 42, 14], float)

In [55]:
# Inner Product
np.inner(arr1, arr2)

2198.0

In [56]:
# outer Product 
np.outer(arr1, arr2)

array([[ 252.,  504.,  168.],
       [ 903., 1806.,  602.],
       [ 210.,  420.,  140.]])

In [57]:
# Cross Product
np.cross(arr1, arr2)

array([ 182.,   42., -399.])

### 5.2 행렬곱

In [58]:
#linear algebra operations
X = np.arange(15).reshape((3, 5))
print(X)
print(X.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [59]:
np.dot(X.T, X)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

### 5.3 행렬식, 역행렬

In [60]:
# 행렬식
matrix = np.array([[74, 22, 10], [92, 31, 17], [21, 22, 12]], float)
print(matrix)
print(np.linalg.det(matrix))

[[74. 22. 10.]
 [92. 31. 17.]
 [21. 22. 12.]]
-2852.000000000003


In [61]:
# 역행렬
inv_matrix = np.linalg.inv(matrix)
print(inv_matrix)
print(np.dot(inv_matrix,matrix))

[[ 0.00070126  0.01542777 -0.02244039]
 [ 0.26192146 -0.23772791  0.11851332]
 [-0.48141655  0.4088359  -0.09467041]]
[[ 1.00000000e+00 -1.66533454e-16 -5.55111512e-17]
 [ 3.99680289e-15  1.00000000e+00  8.88178420e-16]
 [-3.02535774e-15 -1.05471187e-15  1.00000000e+00]]


### 5.4 고윳값, 고유벡터

In [62]:
matrix = np.array([[74, 22, 10], [92, 31, 17], [21, 22, 12]], float)
# 고윳값, 고유벡터
vals, vecs = np.linalg.eig(matrix)
print(vals)

[107.99587441  11.33411853  -2.32999294]


In [63]:
print(vecs)

[[-0.57891525 -0.21517959  0.06319955]
 [-0.75804695  0.17632618 -0.58635713]
 [-0.30036971  0.96052424  0.80758352]]


### 5.5 통계 함수

In [64]:
arr = np.random.rand(8, 4)
arr.mean() # 평균

0.49576006558389374

In [65]:
np.mean(arr) # 평균

0.49576006558389374

In [66]:
arr.std() # 표준 편차

0.2914325371496337

In [67]:
arr.var() # 분산

0.08493292370947261

In [68]:
arr.sum() # 합산

15.8643220986846

In [69]:
arr.min() # 최소

0.04795291931435297

In [70]:
arr.max() # 최대

0.9939627530921408

In [71]:
arr.argmin() # 최소 값의 인덱스

11

In [72]:
arr.argmax() # 최대 값의 인덱스

14